name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy mdBook
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Read .env
        id: mdbook-version
        run: |
          cd docs/
          . ./.env
          echo "::set-output name=MDBOOK_VERSION::${MDBOOK_VERSION}"
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '${{ steps.mdbook-version.outputs.MDBOOK_VERSION }}'
      - run: |
          cd docs/
          mdbook build
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
